// Auto-generated. Blog metadata only (no content). Safe to import from list pages.
export interface BlogPostMeta {
  slug: string;
  toolPath: string;
  title: string;
  category: string;
  excerpt: string;
  readingMinutes: number;
}

export const postsMeta: BlogPostMeta[] = [
  {
    slug: "ai-summarizer",
    toolPath: "/text-tools/ai-summarizer",
    title: "AI Text Summarizer: The Complete Guide",
    category: "Text Tools",
    excerpt: "Turn long articles, reports, and transcripts into short, useful summaries in seconds.",
    readingMinutes: 8,
  },
  {
    slug: "grammar-checker",
    toolPath: "/text-tools/grammar-checker",
    title: "Grammar Checker: The Complete Guide",
    category: "Text Tools",
    excerpt: "Catch spelling slips, awkward phrasing, and punctuation mistakes before anyone else does.",
    readingMinutes: 7,
  },
  {
    slug: "paraphraser",
    toolPath: "/text-tools/paraphraser",
    title: "Paraphrasing Tool: The Complete Guide",
    category: "Text Tools",
    excerpt: "Rewrite any sentence, paragraph, or article in fresh words while keeping the meaning intact.",
    readingMinutes: 7,
  },
  {
    slug: "word-counter",
    toolPath: "/text-tools/word-counter",
    title: "Word Counter: The Complete Guide",
    category: "Text Tools",
    excerpt: "Count words, characters, sentences, and reading time as you type.",
    readingMinutes: 7,
  },
  {
    slug: "case-converter",
    toolPath: "/text-tools/case-converter",
    title: "Case Converter: The Complete Guide",
    category: "Text Tools",
    excerpt: "Instantly switch text between UPPER, lower, Title, and Sentence case.",
    readingMinutes: 7,
  },
  {
    slug: "lorem-ipsum",
    toolPath: "/text-tools/lorem-ipsum",
    title: "Lorem Ipsum Generator: The Complete Guide",
    category: "Text Tools",
    excerpt: "Generate placeholder paragraphs, sentences, or words for design mockups.",
    readingMinutes: 7,
  },
  {
    slug: "compress",
    toolPath: "/image-tools/compress",
    title: "Image Compressor: The Complete Guide",
    category: "Image Tools",
    excerpt: "Shrink JPG and PNG file sizes without visibly losing quality.",
    readingMinutes: 7,
  },
  {
    slug: "resize",
    toolPath: "/image-tools/resize",
    title: "Image Resizer: The Complete Guide",
    category: "Image Tools",
    excerpt: "Resize photos to exact pixel dimensions or a percentage in one click.",
    readingMinutes: 7,
  },
  {
    slug: "jpg-to-png",
    toolPath: "/image-tools/jpg-to-png",
    title: "JPG to PNG Converter: The Complete Guide",
    category: "Image Tools",
    excerpt: "Convert JPG photos to lossless PNG format with transparency support.",
    readingMinutes: 8,
  },
  {
    slug: "png-to-jpg",
    toolPath: "/image-tools/png-to-jpg",
    title: "PNG to JPG Converter: The Complete Guide",
    category: "Image Tools",
    excerpt: "Convert PNG images to smaller JPG files with a background of your choice.",
    readingMinutes: 7,
  },
  {
    slug: "background-remover",
    toolPath: "/image-tools/background-remover",
    title: "Background Remover: The Complete Guide",
    category: "Image Tools",
    excerpt: "Remove image backgrounds automatically with AI in seconds.",
    readingMinutes: 7,
  },
  {
    slug: "qr-code",
    toolPath: "/image-tools/qr-code",
    title: "QR Code Generator: The Complete Guide",
    category: "Image Tools",
    excerpt: "Create QR codes for URLs, text, contact cards, and Wi-Fi credentials in seconds.",
    readingMinutes: 7,
  },
  {
    slug: "image-to-pdf",
    toolPath: "/image-tools/image-to-pdf",
    title: "Image to PDF Converter: The Complete Guide",
    category: "Image Tools",
    excerpt: "Combine one or more images into a single PDF document for easy sharing.",
    readingMinutes: 7,
  },
  {
    slug: "merge",
    toolPath: "/pdf-tools/merge",
    title: "Merge PDF: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Combine two or more PDF files into one document, in any order.",
    readingMinutes: 7,
  },
  {
    slug: "split",
    toolPath: "/pdf-tools/split",
    title: "Split PDF: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Extract page ranges from a PDF into new smaller documents.",
    readingMinutes: 7,
  },
  {
    slug: "compress-pdf",
    toolPath: "/pdf-tools/compress",
    title: "Compress PDF: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Reduce PDF file size for faster sharing and lighter email attachments.",
    readingMinutes: 7,
  },
  {
    slug: "pdf-to-jpg",
    toolPath: "/pdf-tools/pdf-to-jpg",
    title: "PDF to JPG: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Turn each page of a PDF into a JPG image at the resolution you choose.",
    readingMinutes: 7,
  },
  {
    slug: "json-formatter",
    toolPath: "/developer-tools/json-formatter",
    title: "JSON Formatter: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Pretty-print, validate, and explore JSON payloads with clear indentation.",
    readingMinutes: 7,
  },
  {
    slug: "base64-encode",
    toolPath: "/developer-tools/base64-encode",
    title: "Base64 Encoder: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Encode text or files into Base64 for safe use in JSON, URLs, and email.",
    readingMinutes: 7,
  },
  {
    slug: "url-encode",
    toolPath: "/developer-tools/url-encode",
    title: "URL Encoder: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Percent-encode text so it can be safely used in URLs, forms, and query strings.",
    readingMinutes: 7,
  },
  {
    slug: "password-generator",
    toolPath: "/developer-tools/password-generator",
    title: "Password Generator: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Create strong, random passwords tuned to any site's rules.",
    readingMinutes: 7,
  },
  {
    slug: "bmi",
    toolPath: "/calculators/bmi",
    title: "BMI Calculator: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Calculate your body mass index in metric or imperial units.",
    readingMinutes: 7,
  },
  {
    slug: "emi",
    toolPath: "/calculators/emi",
    title: "EMI Calculator: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Estimate monthly loan payments and total interest for any loan.",
    readingMinutes: 7,
  },
  {
    slug: "percentage",
    toolPath: "/calculators/percentage",
    title: "Percentage Calculator: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Solve every common percentage problem in one place.",
    readingMinutes: 7,
  },
  {
    slug: "currency-converter",
    toolPath: "/calculators/currency-converter",
    title: "Currency Converter: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Convert between world currencies using recent exchange rates.",
    readingMinutes: 7,
  },
  {
    slug: "character-counter",
    toolPath: "/text-tools/character-counter",
    title: "Character Counter: The Complete Guide",
    category: "Text Tools",
    excerpt: "Count characters with and without spaces, live as you type.",
    readingMinutes: 7,
  },
  {
    slug: "remove-duplicate-lines",
    toolPath: "/text-tools/remove-duplicate-lines",
    title: "Remove Duplicate Lines: The Complete Guide",
    category: "Text Tools",
    excerpt: "Strip repeated lines from any list, log, or CSV in one click.",
    readingMinutes: 7,
  },
  {
    slug: "text-sorter",
    toolPath: "/text-tools/text-sorter",
    title: "Text Sorter: The Complete Guide",
    category: "Text Tools",
    excerpt: "Sort lines alphabetically, reversed, by length, or randomly in one click.",
    readingMinutes: 7,
  },
  {
    slug: "text-reverser",
    toolPath: "/text-tools/text-reverser",
    title: "Text Reverser: The Complete Guide",
    category: "Text Tools",
    excerpt: "Reverse text by character, word, or line \u2014 perfect for palindromes and puzzles.",
    readingMinutes: 7,
  },
  {
    slug: "crop",
    toolPath: "/image-tools/crop",
    title: "Image Cropper: The Complete Guide",
    category: "Image Tools",
    excerpt: "Crop images to any pixel size, aspect ratio, or freeform selection.",
    readingMinutes: 7,
  },
  {
    slug: "rotate-image",
    toolPath: "/image-tools/rotate",
    title: "Image Rotator: The Complete Guide",
    category: "Image Tools",
    excerpt: "Rotate or flip images in 90-degree steps or by any custom angle.",
    readingMinutes: 7,
  },
  {
    slug: "watermark",
    toolPath: "/image-tools/watermark",
    title: "Watermark Adder: The Complete Guide",
    category: "Image Tools",
    excerpt: "Add a text or logo watermark to protect your images before sharing.",
    readingMinutes: 7,
  },
  {
    slug: "pdf-to-word",
    toolPath: "/pdf-tools/pdf-to-word",
    title: "PDF to Word Converter: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Extract text and simple formatting from a PDF into an editable Word document.",
    readingMinutes: 7,
  },
  {
    slug: "word-to-pdf",
    toolPath: "/pdf-tools/word-to-pdf",
    title: "Word to PDF Converter: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Turn .docx documents into PDF files that look the same everywhere.",
    readingMinutes: 7,
  },
  {
    slug: "jpg-to-pdf",
    toolPath: "/pdf-tools/jpg-to-pdf",
    title: "JPG to PDF: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Combine JPG photos into a single PDF document for easy sharing.",
    readingMinutes: 7,
  },
  {
    slug: "rotate-pdf",
    toolPath: "/pdf-tools/rotate",
    title: "Rotate PDF: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Rotate all pages or specific pages of a PDF in 90-degree steps.",
    readingMinutes: 7,
  },
  {
    slug: "unlock-pdf",
    toolPath: "/pdf-tools/unlock",
    title: "Unlock PDF: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Remove editing and copy restrictions from PDFs you have the right to modify.",
    readingMinutes: 7,
  },
  {
    slug: "page-numbers",
    toolPath: "/pdf-tools/page-numbers",
    title: "Add Page Numbers: The Complete Guide",
    category: "PDF Tools",
    excerpt: "Stamp page numbers onto every page of a PDF with full formatting control.",
    readingMinutes: 7,
  },
  {
    slug: "json-validator",
    toolPath: "/developer-tools/json-validator",
    title: "JSON Validator: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Validate JSON syntax and get precise error messages with line numbers.",
    readingMinutes: 7,
  },
  {
    slug: "base64-decode",
    toolPath: "/developer-tools/base64-decode",
    title: "Base64 Decoder: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Decode Base64-encoded strings back into plain text or downloadable files.",
    readingMinutes: 7,
  },
  {
    slug: "url-decode",
    toolPath: "/developer-tools/url-decode",
    title: "URL Decoder: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Convert percent-encoded URLs back into readable plain text.",
    readingMinutes: 7,
  },
  {
    slug: "html-minifier",
    toolPath: "/developer-tools/html-minifier",
    title: "HTML Minifier: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Shrink HTML by removing comments, whitespace, and redundant attributes.",
    readingMinutes: 7,
  },
  {
    slug: "css-minifier",
    toolPath: "/developer-tools/css-minifier",
    title: "CSS Minifier: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Compress CSS by removing comments, whitespace, and merging shorthand.",
    readingMinutes: 7,
  },
  {
    slug: "js-minifier",
    toolPath: "/developer-tools/js-minifier",
    title: "JavaScript Minifier: The Complete Guide",
    category: "Developer Tools",
    excerpt: "Lightly minify JavaScript by stripping comments, whitespace, and dead code.",
    readingMinutes: 7,
  },
  {
    slug: "age-calculator",
    toolPath: "/calculators/age",
    title: "Age Calculator: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Work out exact age in years, months, days, hours, and minutes.",
    readingMinutes: 7,
  },
  {
    slug: "gst-vat",
    toolPath: "/calculators/gst-vat",
    title: "GST / VAT Calculator: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Add or remove GST, VAT, or any sales tax from a price in seconds.",
    readingMinutes: 7,
  },
  {
    slug: "length-converter",
    toolPath: "/calculators/length",
    title: "Length Converter: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Convert between metric and imperial lengths \u2014 meters, feet, inches, miles, and more.",
    readingMinutes: 7,
  },
  {
    slug: "weight-converter",
    toolPath: "/calculators/weight",
    title: "Weight Converter: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Convert kilograms, pounds, ounces, grams, and stones instantly.",
    readingMinutes: 7,
  },
  {
    slug: "temperature-converter",
    toolPath: "/calculators/temperature",
    title: "Temperature Converter: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Convert between Celsius, Fahrenheit, Kelvin, and Rankine.",
    readingMinutes: 7,
  },
  {
    slug: "binary-to-decimal",
    toolPath: "/calculators/binary-to-decimal",
    title: "Binary to Decimal Converter: The Complete Guide",
    category: "Calculators & Converters",
    excerpt: "Convert binary numbers to decimal, hex, and octal in one place.",
    readingMinutes: 7,
  },
];

export function getPostMeta(slug: string): BlogPostMeta | undefined {
  return postsMeta.find((p) => p.slug === slug);
}