/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TextToolsIndexRouteImport } from './routes/text-tools.index'
import { Route as PdfToolsIndexRouteImport } from './routes/pdf-tools.index'
import { Route as ImageToolsIndexRouteImport } from './routes/image-tools.index'
import { Route as DeveloperToolsIndexRouteImport } from './routes/developer-tools.index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators.index'
import { Route as TextToolsWordCounterRouteImport } from './routes/text-tools.word-counter'
import { Route as TextToolsTextSorterRouteImport } from './routes/text-tools.text-sorter'
import { Route as TextToolsTextReverserRouteImport } from './routes/text-tools.text-reverser'
import { Route as TextToolsRemoveDuplicateLinesRouteImport } from './routes/text-tools.remove-duplicate-lines'
import { Route as TextToolsParaphraserRouteImport } from './routes/text-tools.paraphraser'
import { Route as TextToolsLoremIpsumRouteImport } from './routes/text-tools.lorem-ipsum'
import { Route as TextToolsGrammarCheckerRouteImport } from './routes/text-tools.grammar-checker'
import { Route as TextToolsCharacterCounterRouteImport } from './routes/text-tools.character-counter'
import { Route as TextToolsCaseConverterRouteImport } from './routes/text-tools.case-converter'
import { Route as TextToolsAiSummarizerRouteImport } from './routes/text-tools.ai-summarizer'
import { Route as ImageToolsWatermarkRouteImport } from './routes/image-tools.watermark'
import { Route as ImageToolsRotateRouteImport } from './routes/image-tools.rotate'
import { Route as ImageToolsResizeRouteImport } from './routes/image-tools.resize'
import { Route as ImageToolsQrCodeRouteImport } from './routes/image-tools.qr-code'
import { Route as ImageToolsPngToJpgRouteImport } from './routes/image-tools.png-to-jpg'
import { Route as ImageToolsJpgToPngRouteImport } from './routes/image-tools.jpg-to-png'
import { Route as ImageToolsImageToPdfRouteImport } from './routes/image-tools.image-to-pdf'
import { Route as ImageToolsCropRouteImport } from './routes/image-tools.crop'
import { Route as ImageToolsCompressRouteImport } from './routes/image-tools.compress'
import { Route as ImageToolsBackgroundRemoverRouteImport } from './routes/image-tools.background-remover'
import { Route as DeveloperToolsUrlEncodeRouteImport } from './routes/developer-tools.url-encode'
import { Route as DeveloperToolsUrlDecodeRouteImport } from './routes/developer-tools.url-decode'
import { Route as DeveloperToolsPasswordGeneratorRouteImport } from './routes/developer-tools.password-generator'
import { Route as DeveloperToolsJsonValidatorRouteImport } from './routes/developer-tools.json-validator'
import { Route as DeveloperToolsJsonFormatterRouteImport } from './routes/developer-tools.json-formatter'
import { Route as DeveloperToolsJsMinifierRouteImport } from './routes/developer-tools.js-minifier'
import { Route as DeveloperToolsHtmlMinifierRouteImport } from './routes/developer-tools.html-minifier'
import { Route as DeveloperToolsCssMinifierRouteImport } from './routes/developer-tools.css-minifier'
import { Route as DeveloperToolsBase64EncodeRouteImport } from './routes/developer-tools.base64-encode'
import { Route as DeveloperToolsBase64DecodeRouteImport } from './routes/developer-tools.base64-decode'
import { Route as CalculatorsWeightRouteImport } from './routes/calculators.weight'
import { Route as CalculatorsTemperatureRouteImport } from './routes/calculators.temperature'
import { Route as CalculatorsPercentageRouteImport } from './routes/calculators.percentage'
import { Route as CalculatorsLengthRouteImport } from './routes/calculators.length'
import { Route as CalculatorsGstVatRouteImport } from './routes/calculators.gst-vat'
import { Route as CalculatorsEmiRouteImport } from './routes/calculators.emi'
import { Route as CalculatorsCurrencyConverterRouteImport } from './routes/calculators.currency-converter'
import { Route as CalculatorsBmiRouteImport } from './routes/calculators.bmi'
import { Route as CalculatorsBinaryToDecimalRouteImport } from './routes/calculators.binary-to-decimal'
import { Route as CalculatorsAgeRouteImport } from './routes/calculators.age'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsIndexRoute = TextToolsIndexRouteImport.update({
  id: '/text-tools/',
  path: '/text-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToolsIndexRoute = PdfToolsIndexRouteImport.update({
  id: '/pdf-tools/',
  path: '/pdf-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsIndexRoute = ImageToolsIndexRouteImport.update({
  id: '/image-tools/',
  path: '/image-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperToolsIndexRoute = DeveloperToolsIndexRouteImport.update({
  id: '/developer-tools/',
  path: '/developer-tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsWordCounterRoute = TextToolsWordCounterRouteImport.update({
  id: '/text-tools/word-counter',
  path: '/text-tools/word-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsTextSorterRoute = TextToolsTextSorterRouteImport.update({
  id: '/text-tools/text-sorter',
  path: '/text-tools/text-sorter',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsTextReverserRoute = TextToolsTextReverserRouteImport.update({
  id: '/text-tools/text-reverser',
  path: '/text-tools/text-reverser',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsRemoveDuplicateLinesRoute =
  TextToolsRemoveDuplicateLinesRouteImport.update({
    id: '/text-tools/remove-duplicate-lines',
    path: '/text-tools/remove-duplicate-lines',
    getParentRoute: () => rootRouteImport,
  } as any)
const TextToolsParaphraserRoute = TextToolsParaphraserRouteImport.update({
  id: '/text-tools/paraphraser',
  path: '/text-tools/paraphraser',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsLoremIpsumRoute = TextToolsLoremIpsumRouteImport.update({
  id: '/text-tools/lorem-ipsum',
  path: '/text-tools/lorem-ipsum',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsGrammarCheckerRoute = TextToolsGrammarCheckerRouteImport.update({
  id: '/text-tools/grammar-checker',
  path: '/text-tools/grammar-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsCharacterCounterRoute =
  TextToolsCharacterCounterRouteImport.update({
    id: '/text-tools/character-counter',
    path: '/text-tools/character-counter',
    getParentRoute: () => rootRouteImport,
  } as any)
const TextToolsCaseConverterRoute = TextToolsCaseConverterRouteImport.update({
  id: '/text-tools/case-converter',
  path: '/text-tools/case-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToolsAiSummarizerRoute = TextToolsAiSummarizerRouteImport.update({
  id: '/text-tools/ai-summarizer',
  path: '/text-tools/ai-summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsWatermarkRoute = ImageToolsWatermarkRouteImport.update({
  id: '/image-tools/watermark',
  path: '/image-tools/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsRotateRoute = ImageToolsRotateRouteImport.update({
  id: '/image-tools/rotate',
  path: '/image-tools/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsResizeRoute = ImageToolsResizeRouteImport.update({
  id: '/image-tools/resize',
  path: '/image-tools/resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsQrCodeRoute = ImageToolsQrCodeRouteImport.update({
  id: '/image-tools/qr-code',
  path: '/image-tools/qr-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsPngToJpgRoute = ImageToolsPngToJpgRouteImport.update({
  id: '/image-tools/png-to-jpg',
  path: '/image-tools/png-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsJpgToPngRoute = ImageToolsJpgToPngRouteImport.update({
  id: '/image-tools/jpg-to-png',
  path: '/image-tools/jpg-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsImageToPdfRoute = ImageToolsImageToPdfRouteImport.update({
  id: '/image-tools/image-to-pdf',
  path: '/image-tools/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsCropRoute = ImageToolsCropRouteImport.update({
  id: '/image-tools/crop',
  path: '/image-tools/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsCompressRoute = ImageToolsCompressRouteImport.update({
  id: '/image-tools/compress',
  path: '/image-tools/compress',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToolsBackgroundRemoverRoute =
  ImageToolsBackgroundRemoverRouteImport.update({
    id: '/image-tools/background-remover',
    path: '/image-tools/background-remover',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsUrlEncodeRoute = DeveloperToolsUrlEncodeRouteImport.update({
  id: '/developer-tools/url-encode',
  path: '/developer-tools/url-encode',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperToolsUrlDecodeRoute = DeveloperToolsUrlDecodeRouteImport.update({
  id: '/developer-tools/url-decode',
  path: '/developer-tools/url-decode',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperToolsPasswordGeneratorRoute =
  DeveloperToolsPasswordGeneratorRouteImport.update({
    id: '/developer-tools/password-generator',
    path: '/developer-tools/password-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsJsonValidatorRoute =
  DeveloperToolsJsonValidatorRouteImport.update({
    id: '/developer-tools/json-validator',
    path: '/developer-tools/json-validator',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsJsonFormatterRoute =
  DeveloperToolsJsonFormatterRouteImport.update({
    id: '/developer-tools/json-formatter',
    path: '/developer-tools/json-formatter',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsJsMinifierRoute =
  DeveloperToolsJsMinifierRouteImport.update({
    id: '/developer-tools/js-minifier',
    path: '/developer-tools/js-minifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsHtmlMinifierRoute =
  DeveloperToolsHtmlMinifierRouteImport.update({
    id: '/developer-tools/html-minifier',
    path: '/developer-tools/html-minifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsCssMinifierRoute =
  DeveloperToolsCssMinifierRouteImport.update({
    id: '/developer-tools/css-minifier',
    path: '/developer-tools/css-minifier',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsBase64EncodeRoute =
  DeveloperToolsBase64EncodeRouteImport.update({
    id: '/developer-tools/base64-encode',
    path: '/developer-tools/base64-encode',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperToolsBase64DecodeRoute =
  DeveloperToolsBase64DecodeRouteImport.update({
    id: '/developer-tools/base64-decode',
    path: '/developer-tools/base64-decode',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsWeightRoute = CalculatorsWeightRouteImport.update({
  id: '/calculators/weight',
  path: '/calculators/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsTemperatureRoute = CalculatorsTemperatureRouteImport.update({
  id: '/calculators/temperature',
  path: '/calculators/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsPercentageRoute = CalculatorsPercentageRouteImport.update({
  id: '/calculators/percentage',
  path: '/calculators/percentage',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsLengthRoute = CalculatorsLengthRouteImport.update({
  id: '/calculators/length',
  path: '/calculators/length',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsGstVatRoute = CalculatorsGstVatRouteImport.update({
  id: '/calculators/gst-vat',
  path: '/calculators/gst-vat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsEmiRoute = CalculatorsEmiRouteImport.update({
  id: '/calculators/emi',
  path: '/calculators/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsCurrencyConverterRoute =
  CalculatorsCurrencyConverterRouteImport.update({
    id: '/calculators/currency-converter',
    path: '/calculators/currency-converter',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsBmiRoute = CalculatorsBmiRouteImport.update({
  id: '/calculators/bmi',
  path: '/calculators/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsBinaryToDecimalRoute =
  CalculatorsBinaryToDecimalRouteImport.update({
    id: '/calculators/binary-to-decimal',
    path: '/calculators/binary-to-decimal',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculatorsAgeRoute = CalculatorsAgeRouteImport.update({
  id: '/calculators/age',
  path: '/calculators/age',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculators/age': typeof CalculatorsAgeRoute
  '/calculators/binary-to-decimal': typeof CalculatorsBinaryToDecimalRoute
  '/calculators/bmi': typeof CalculatorsBmiRoute
  '/calculators/currency-converter': typeof CalculatorsCurrencyConverterRoute
  '/calculators/emi': typeof CalculatorsEmiRoute
  '/calculators/gst-vat': typeof CalculatorsGstVatRoute
  '/calculators/length': typeof CalculatorsLengthRoute
  '/calculators/percentage': typeof CalculatorsPercentageRoute
  '/calculators/temperature': typeof CalculatorsTemperatureRoute
  '/calculators/weight': typeof CalculatorsWeightRoute
  '/developer-tools/base64-decode': typeof DeveloperToolsBase64DecodeRoute
  '/developer-tools/base64-encode': typeof DeveloperToolsBase64EncodeRoute
  '/developer-tools/css-minifier': typeof DeveloperToolsCssMinifierRoute
  '/developer-tools/html-minifier': typeof DeveloperToolsHtmlMinifierRoute
  '/developer-tools/js-minifier': typeof DeveloperToolsJsMinifierRoute
  '/developer-tools/json-formatter': typeof DeveloperToolsJsonFormatterRoute
  '/developer-tools/json-validator': typeof DeveloperToolsJsonValidatorRoute
  '/developer-tools/password-generator': typeof DeveloperToolsPasswordGeneratorRoute
  '/developer-tools/url-decode': typeof DeveloperToolsUrlDecodeRoute
  '/developer-tools/url-encode': typeof DeveloperToolsUrlEncodeRoute
  '/image-tools/background-remover': typeof ImageToolsBackgroundRemoverRoute
  '/image-tools/compress': typeof ImageToolsCompressRoute
  '/image-tools/crop': typeof ImageToolsCropRoute
  '/image-tools/image-to-pdf': typeof ImageToolsImageToPdfRoute
  '/image-tools/jpg-to-png': typeof ImageToolsJpgToPngRoute
  '/image-tools/png-to-jpg': typeof ImageToolsPngToJpgRoute
  '/image-tools/qr-code': typeof ImageToolsQrCodeRoute
  '/image-tools/resize': typeof ImageToolsResizeRoute
  '/image-tools/rotate': typeof ImageToolsRotateRoute
  '/image-tools/watermark': typeof ImageToolsWatermarkRoute
  '/text-tools/ai-summarizer': typeof TextToolsAiSummarizerRoute
  '/text-tools/case-converter': typeof TextToolsCaseConverterRoute
  '/text-tools/character-counter': typeof TextToolsCharacterCounterRoute
  '/text-tools/grammar-checker': typeof TextToolsGrammarCheckerRoute
  '/text-tools/lorem-ipsum': typeof TextToolsLoremIpsumRoute
  '/text-tools/paraphraser': typeof TextToolsParaphraserRoute
  '/text-tools/remove-duplicate-lines': typeof TextToolsRemoveDuplicateLinesRoute
  '/text-tools/text-reverser': typeof TextToolsTextReverserRoute
  '/text-tools/text-sorter': typeof TextToolsTextSorterRoute
  '/text-tools/word-counter': typeof TextToolsWordCounterRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/developer-tools/': typeof DeveloperToolsIndexRoute
  '/image-tools/': typeof ImageToolsIndexRoute
  '/pdf-tools/': typeof PdfToolsIndexRoute
  '/text-tools/': typeof TextToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculators/age': typeof CalculatorsAgeRoute
  '/calculators/binary-to-decimal': typeof CalculatorsBinaryToDecimalRoute
  '/calculators/bmi': typeof CalculatorsBmiRoute
  '/calculators/currency-converter': typeof CalculatorsCurrencyConverterRoute
  '/calculators/emi': typeof CalculatorsEmiRoute
  '/calculators/gst-vat': typeof CalculatorsGstVatRoute
  '/calculators/length': typeof CalculatorsLengthRoute
  '/calculators/percentage': typeof CalculatorsPercentageRoute
  '/calculators/temperature': typeof CalculatorsTemperatureRoute
  '/calculators/weight': typeof CalculatorsWeightRoute
  '/developer-tools/base64-decode': typeof DeveloperToolsBase64DecodeRoute
  '/developer-tools/base64-encode': typeof DeveloperToolsBase64EncodeRoute
  '/developer-tools/css-minifier': typeof DeveloperToolsCssMinifierRoute
  '/developer-tools/html-minifier': typeof DeveloperToolsHtmlMinifierRoute
  '/developer-tools/js-minifier': typeof DeveloperToolsJsMinifierRoute
  '/developer-tools/json-formatter': typeof DeveloperToolsJsonFormatterRoute
  '/developer-tools/json-validator': typeof DeveloperToolsJsonValidatorRoute
  '/developer-tools/password-generator': typeof DeveloperToolsPasswordGeneratorRoute
  '/developer-tools/url-decode': typeof DeveloperToolsUrlDecodeRoute
  '/developer-tools/url-encode': typeof DeveloperToolsUrlEncodeRoute
  '/image-tools/background-remover': typeof ImageToolsBackgroundRemoverRoute
  '/image-tools/compress': typeof ImageToolsCompressRoute
  '/image-tools/crop': typeof ImageToolsCropRoute
  '/image-tools/image-to-pdf': typeof ImageToolsImageToPdfRoute
  '/image-tools/jpg-to-png': typeof ImageToolsJpgToPngRoute
  '/image-tools/png-to-jpg': typeof ImageToolsPngToJpgRoute
  '/image-tools/qr-code': typeof ImageToolsQrCodeRoute
  '/image-tools/resize': typeof ImageToolsResizeRoute
  '/image-tools/rotate': typeof ImageToolsRotateRoute
  '/image-tools/watermark': typeof ImageToolsWatermarkRoute
  '/text-tools/ai-summarizer': typeof TextToolsAiSummarizerRoute
  '/text-tools/case-converter': typeof TextToolsCaseConverterRoute
  '/text-tools/character-counter': typeof TextToolsCharacterCounterRoute
  '/text-tools/grammar-checker': typeof TextToolsGrammarCheckerRoute
  '/text-tools/lorem-ipsum': typeof TextToolsLoremIpsumRoute
  '/text-tools/paraphraser': typeof TextToolsParaphraserRoute
  '/text-tools/remove-duplicate-lines': typeof TextToolsRemoveDuplicateLinesRoute
  '/text-tools/text-reverser': typeof TextToolsTextReverserRoute
  '/text-tools/text-sorter': typeof TextToolsTextSorterRoute
  '/text-tools/word-counter': typeof TextToolsWordCounterRoute
  '/calculators': typeof CalculatorsIndexRoute
  '/developer-tools': typeof DeveloperToolsIndexRoute
  '/image-tools': typeof ImageToolsIndexRoute
  '/pdf-tools': typeof PdfToolsIndexRoute
  '/text-tools': typeof TextToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculators/age': typeof CalculatorsAgeRoute
  '/calculators/binary-to-decimal': typeof CalculatorsBinaryToDecimalRoute
  '/calculators/bmi': typeof CalculatorsBmiRoute
  '/calculators/currency-converter': typeof CalculatorsCurrencyConverterRoute
  '/calculators/emi': typeof CalculatorsEmiRoute
  '/calculators/gst-vat': typeof CalculatorsGstVatRoute
  '/calculators/length': typeof CalculatorsLengthRoute
  '/calculators/percentage': typeof CalculatorsPercentageRoute
  '/calculators/temperature': typeof CalculatorsTemperatureRoute
  '/calculators/weight': typeof CalculatorsWeightRoute
  '/developer-tools/base64-decode': typeof DeveloperToolsBase64DecodeRoute
  '/developer-tools/base64-encode': typeof DeveloperToolsBase64EncodeRoute
  '/developer-tools/css-minifier': typeof DeveloperToolsCssMinifierRoute
  '/developer-tools/html-minifier': typeof DeveloperToolsHtmlMinifierRoute
  '/developer-tools/js-minifier': typeof DeveloperToolsJsMinifierRoute
  '/developer-tools/json-formatter': typeof DeveloperToolsJsonFormatterRoute
  '/developer-tools/json-validator': typeof DeveloperToolsJsonValidatorRoute
  '/developer-tools/password-generator': typeof DeveloperToolsPasswordGeneratorRoute
  '/developer-tools/url-decode': typeof DeveloperToolsUrlDecodeRoute
  '/developer-tools/url-encode': typeof DeveloperToolsUrlEncodeRoute
  '/image-tools/background-remover': typeof ImageToolsBackgroundRemoverRoute
  '/image-tools/compress': typeof ImageToolsCompressRoute
  '/image-tools/crop': typeof ImageToolsCropRoute
  '/image-tools/image-to-pdf': typeof ImageToolsImageToPdfRoute
  '/image-tools/jpg-to-png': typeof ImageToolsJpgToPngRoute
  '/image-tools/png-to-jpg': typeof ImageToolsPngToJpgRoute
  '/image-tools/qr-code': typeof ImageToolsQrCodeRoute
  '/image-tools/resize': typeof ImageToolsResizeRoute
  '/image-tools/rotate': typeof ImageToolsRotateRoute
  '/image-tools/watermark': typeof ImageToolsWatermarkRoute
  '/text-tools/ai-summarizer': typeof TextToolsAiSummarizerRoute
  '/text-tools/case-converter': typeof TextToolsCaseConverterRoute
  '/text-tools/character-counter': typeof TextToolsCharacterCounterRoute
  '/text-tools/grammar-checker': typeof TextToolsGrammarCheckerRoute
  '/text-tools/lorem-ipsum': typeof TextToolsLoremIpsumRoute
  '/text-tools/paraphraser': typeof TextToolsParaphraserRoute
  '/text-tools/remove-duplicate-lines': typeof TextToolsRemoveDuplicateLinesRoute
  '/text-tools/text-reverser': typeof TextToolsTextReverserRoute
  '/text-tools/text-sorter': typeof TextToolsTextSorterRoute
  '/text-tools/word-counter': typeof TextToolsWordCounterRoute
  '/calculators/': typeof CalculatorsIndexRoute
  '/developer-tools/': typeof DeveloperToolsIndexRoute
  '/image-tools/': typeof ImageToolsIndexRoute
  '/pdf-tools/': typeof PdfToolsIndexRoute
  '/text-tools/': typeof TextToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculators/age'
    | '/calculators/binary-to-decimal'
    | '/calculators/bmi'
    | '/calculators/currency-converter'
    | '/calculators/emi'
    | '/calculators/gst-vat'
    | '/calculators/length'
    | '/calculators/percentage'
    | '/calculators/temperature'
    | '/calculators/weight'
    | '/developer-tools/base64-decode'
    | '/developer-tools/base64-encode'
    | '/developer-tools/css-minifier'
    | '/developer-tools/html-minifier'
    | '/developer-tools/js-minifier'
    | '/developer-tools/json-formatter'
    | '/developer-tools/json-validator'
    | '/developer-tools/password-generator'
    | '/developer-tools/url-decode'
    | '/developer-tools/url-encode'
    | '/image-tools/background-remover'
    | '/image-tools/compress'
    | '/image-tools/crop'
    | '/image-tools/image-to-pdf'
    | '/image-tools/jpg-to-png'
    | '/image-tools/png-to-jpg'
    | '/image-tools/qr-code'
    | '/image-tools/resize'
    | '/image-tools/rotate'
    | '/image-tools/watermark'
    | '/text-tools/ai-summarizer'
    | '/text-tools/case-converter'
    | '/text-tools/character-counter'
    | '/text-tools/grammar-checker'
    | '/text-tools/lorem-ipsum'
    | '/text-tools/paraphraser'
    | '/text-tools/remove-duplicate-lines'
    | '/text-tools/text-reverser'
    | '/text-tools/text-sorter'
    | '/text-tools/word-counter'
    | '/calculators/'
    | '/developer-tools/'
    | '/image-tools/'
    | '/pdf-tools/'
    | '/text-tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculators/age'
    | '/calculators/binary-to-decimal'
    | '/calculators/bmi'
    | '/calculators/currency-converter'
    | '/calculators/emi'
    | '/calculators/gst-vat'
    | '/calculators/length'
    | '/calculators/percentage'
    | '/calculators/temperature'
    | '/calculators/weight'
    | '/developer-tools/base64-decode'
    | '/developer-tools/base64-encode'
    | '/developer-tools/css-minifier'
    | '/developer-tools/html-minifier'
    | '/developer-tools/js-minifier'
    | '/developer-tools/json-formatter'
    | '/developer-tools/json-validator'
    | '/developer-tools/password-generator'
    | '/developer-tools/url-decode'
    | '/developer-tools/url-encode'
    | '/image-tools/background-remover'
    | '/image-tools/compress'
    | '/image-tools/crop'
    | '/image-tools/image-to-pdf'
    | '/image-tools/jpg-to-png'
    | '/image-tools/png-to-jpg'
    | '/image-tools/qr-code'
    | '/image-tools/resize'
    | '/image-tools/rotate'
    | '/image-tools/watermark'
    | '/text-tools/ai-summarizer'
    | '/text-tools/case-converter'
    | '/text-tools/character-counter'
    | '/text-tools/grammar-checker'
    | '/text-tools/lorem-ipsum'
    | '/text-tools/paraphraser'
    | '/text-tools/remove-duplicate-lines'
    | '/text-tools/text-reverser'
    | '/text-tools/text-sorter'
    | '/text-tools/word-counter'
    | '/calculators'
    | '/developer-tools'
    | '/image-tools'
    | '/pdf-tools'
    | '/text-tools'
  id:
    | '__root__'
    | '/'
    | '/calculators/age'
    | '/calculators/binary-to-decimal'
    | '/calculators/bmi'
    | '/calculators/currency-converter'
    | '/calculators/emi'
    | '/calculators/gst-vat'
    | '/calculators/length'
    | '/calculators/percentage'
    | '/calculators/temperature'
    | '/calculators/weight'
    | '/developer-tools/base64-decode'
    | '/developer-tools/base64-encode'
    | '/developer-tools/css-minifier'
    | '/developer-tools/html-minifier'
    | '/developer-tools/js-minifier'
    | '/developer-tools/json-formatter'
    | '/developer-tools/json-validator'
    | '/developer-tools/password-generator'
    | '/developer-tools/url-decode'
    | '/developer-tools/url-encode'
    | '/image-tools/background-remover'
    | '/image-tools/compress'
    | '/image-tools/crop'
    | '/image-tools/image-to-pdf'
    | '/image-tools/jpg-to-png'
    | '/image-tools/png-to-jpg'
    | '/image-tools/qr-code'
    | '/image-tools/resize'
    | '/image-tools/rotate'
    | '/image-tools/watermark'
    | '/text-tools/ai-summarizer'
    | '/text-tools/case-converter'
    | '/text-tools/character-counter'
    | '/text-tools/grammar-checker'
    | '/text-tools/lorem-ipsum'
    | '/text-tools/paraphraser'
    | '/text-tools/remove-duplicate-lines'
    | '/text-tools/text-reverser'
    | '/text-tools/text-sorter'
    | '/text-tools/word-counter'
    | '/calculators/'
    | '/developer-tools/'
    | '/image-tools/'
    | '/pdf-tools/'
    | '/text-tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsAgeRoute: typeof CalculatorsAgeRoute
  CalculatorsBinaryToDecimalRoute: typeof CalculatorsBinaryToDecimalRoute
  CalculatorsBmiRoute: typeof CalculatorsBmiRoute
  CalculatorsCurrencyConverterRoute: typeof CalculatorsCurrencyConverterRoute
  CalculatorsEmiRoute: typeof CalculatorsEmiRoute
  CalculatorsGstVatRoute: typeof CalculatorsGstVatRoute
  CalculatorsLengthRoute: typeof CalculatorsLengthRoute
  CalculatorsPercentageRoute: typeof CalculatorsPercentageRoute
  CalculatorsTemperatureRoute: typeof CalculatorsTemperatureRoute
  CalculatorsWeightRoute: typeof CalculatorsWeightRoute
  DeveloperToolsBase64DecodeRoute: typeof DeveloperToolsBase64DecodeRoute
  DeveloperToolsBase64EncodeRoute: typeof DeveloperToolsBase64EncodeRoute
  DeveloperToolsCssMinifierRoute: typeof DeveloperToolsCssMinifierRoute
  DeveloperToolsHtmlMinifierRoute: typeof DeveloperToolsHtmlMinifierRoute
  DeveloperToolsJsMinifierRoute: typeof DeveloperToolsJsMinifierRoute
  DeveloperToolsJsonFormatterRoute: typeof DeveloperToolsJsonFormatterRoute
  DeveloperToolsJsonValidatorRoute: typeof DeveloperToolsJsonValidatorRoute
  DeveloperToolsPasswordGeneratorRoute: typeof DeveloperToolsPasswordGeneratorRoute
  DeveloperToolsUrlDecodeRoute: typeof DeveloperToolsUrlDecodeRoute
  DeveloperToolsUrlEncodeRoute: typeof DeveloperToolsUrlEncodeRoute
  ImageToolsBackgroundRemoverRoute: typeof ImageToolsBackgroundRemoverRoute
  ImageToolsCompressRoute: typeof ImageToolsCompressRoute
  ImageToolsCropRoute: typeof ImageToolsCropRoute
  ImageToolsImageToPdfRoute: typeof ImageToolsImageToPdfRoute
  ImageToolsJpgToPngRoute: typeof ImageToolsJpgToPngRoute
  ImageToolsPngToJpgRoute: typeof ImageToolsPngToJpgRoute
  ImageToolsQrCodeRoute: typeof ImageToolsQrCodeRoute
  ImageToolsResizeRoute: typeof ImageToolsResizeRoute
  ImageToolsRotateRoute: typeof ImageToolsRotateRoute
  ImageToolsWatermarkRoute: typeof ImageToolsWatermarkRoute
  TextToolsAiSummarizerRoute: typeof TextToolsAiSummarizerRoute
  TextToolsCaseConverterRoute: typeof TextToolsCaseConverterRoute
  TextToolsCharacterCounterRoute: typeof TextToolsCharacterCounterRoute
  TextToolsGrammarCheckerRoute: typeof TextToolsGrammarCheckerRoute
  TextToolsLoremIpsumRoute: typeof TextToolsLoremIpsumRoute
  TextToolsParaphraserRoute: typeof TextToolsParaphraserRoute
  TextToolsRemoveDuplicateLinesRoute: typeof TextToolsRemoveDuplicateLinesRoute
  TextToolsTextReverserRoute: typeof TextToolsTextReverserRoute
  TextToolsTextSorterRoute: typeof TextToolsTextSorterRoute
  TextToolsWordCounterRoute: typeof TextToolsWordCounterRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
  DeveloperToolsIndexRoute: typeof DeveloperToolsIndexRoute
  ImageToolsIndexRoute: typeof ImageToolsIndexRoute
  PdfToolsIndexRoute: typeof PdfToolsIndexRoute
  TextToolsIndexRoute: typeof TextToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/': {
      id: '/text-tools/'
      path: '/text-tools'
      fullPath: '/text-tools/'
      preLoaderRoute: typeof TextToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-tools/': {
      id: '/pdf-tools/'
      path: '/pdf-tools'
      fullPath: '/pdf-tools/'
      preLoaderRoute: typeof PdfToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/': {
      id: '/image-tools/'
      path: '/image-tools'
      fullPath: '/image-tools/'
      preLoaderRoute: typeof ImageToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/': {
      id: '/developer-tools/'
      path: '/developer-tools'
      fullPath: '/developer-tools/'
      preLoaderRoute: typeof DeveloperToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/word-counter': {
      id: '/text-tools/word-counter'
      path: '/text-tools/word-counter'
      fullPath: '/text-tools/word-counter'
      preLoaderRoute: typeof TextToolsWordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/text-sorter': {
      id: '/text-tools/text-sorter'
      path: '/text-tools/text-sorter'
      fullPath: '/text-tools/text-sorter'
      preLoaderRoute: typeof TextToolsTextSorterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/text-reverser': {
      id: '/text-tools/text-reverser'
      path: '/text-tools/text-reverser'
      fullPath: '/text-tools/text-reverser'
      preLoaderRoute: typeof TextToolsTextReverserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/remove-duplicate-lines': {
      id: '/text-tools/remove-duplicate-lines'
      path: '/text-tools/remove-duplicate-lines'
      fullPath: '/text-tools/remove-duplicate-lines'
      preLoaderRoute: typeof TextToolsRemoveDuplicateLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/paraphraser': {
      id: '/text-tools/paraphraser'
      path: '/text-tools/paraphraser'
      fullPath: '/text-tools/paraphraser'
      preLoaderRoute: typeof TextToolsParaphraserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/lorem-ipsum': {
      id: '/text-tools/lorem-ipsum'
      path: '/text-tools/lorem-ipsum'
      fullPath: '/text-tools/lorem-ipsum'
      preLoaderRoute: typeof TextToolsLoremIpsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/grammar-checker': {
      id: '/text-tools/grammar-checker'
      path: '/text-tools/grammar-checker'
      fullPath: '/text-tools/grammar-checker'
      preLoaderRoute: typeof TextToolsGrammarCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/character-counter': {
      id: '/text-tools/character-counter'
      path: '/text-tools/character-counter'
      fullPath: '/text-tools/character-counter'
      preLoaderRoute: typeof TextToolsCharacterCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/case-converter': {
      id: '/text-tools/case-converter'
      path: '/text-tools/case-converter'
      fullPath: '/text-tools/case-converter'
      preLoaderRoute: typeof TextToolsCaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-tools/ai-summarizer': {
      id: '/text-tools/ai-summarizer'
      path: '/text-tools/ai-summarizer'
      fullPath: '/text-tools/ai-summarizer'
      preLoaderRoute: typeof TextToolsAiSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/watermark': {
      id: '/image-tools/watermark'
      path: '/image-tools/watermark'
      fullPath: '/image-tools/watermark'
      preLoaderRoute: typeof ImageToolsWatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/rotate': {
      id: '/image-tools/rotate'
      path: '/image-tools/rotate'
      fullPath: '/image-tools/rotate'
      preLoaderRoute: typeof ImageToolsRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/resize': {
      id: '/image-tools/resize'
      path: '/image-tools/resize'
      fullPath: '/image-tools/resize'
      preLoaderRoute: typeof ImageToolsResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/qr-code': {
      id: '/image-tools/qr-code'
      path: '/image-tools/qr-code'
      fullPath: '/image-tools/qr-code'
      preLoaderRoute: typeof ImageToolsQrCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/png-to-jpg': {
      id: '/image-tools/png-to-jpg'
      path: '/image-tools/png-to-jpg'
      fullPath: '/image-tools/png-to-jpg'
      preLoaderRoute: typeof ImageToolsPngToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/jpg-to-png': {
      id: '/image-tools/jpg-to-png'
      path: '/image-tools/jpg-to-png'
      fullPath: '/image-tools/jpg-to-png'
      preLoaderRoute: typeof ImageToolsJpgToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/image-to-pdf': {
      id: '/image-tools/image-to-pdf'
      path: '/image-tools/image-to-pdf'
      fullPath: '/image-tools/image-to-pdf'
      preLoaderRoute: typeof ImageToolsImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/crop': {
      id: '/image-tools/crop'
      path: '/image-tools/crop'
      fullPath: '/image-tools/crop'
      preLoaderRoute: typeof ImageToolsCropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/compress': {
      id: '/image-tools/compress'
      path: '/image-tools/compress'
      fullPath: '/image-tools/compress'
      preLoaderRoute: typeof ImageToolsCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-tools/background-remover': {
      id: '/image-tools/background-remover'
      path: '/image-tools/background-remover'
      fullPath: '/image-tools/background-remover'
      preLoaderRoute: typeof ImageToolsBackgroundRemoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/url-encode': {
      id: '/developer-tools/url-encode'
      path: '/developer-tools/url-encode'
      fullPath: '/developer-tools/url-encode'
      preLoaderRoute: typeof DeveloperToolsUrlEncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/url-decode': {
      id: '/developer-tools/url-decode'
      path: '/developer-tools/url-decode'
      fullPath: '/developer-tools/url-decode'
      preLoaderRoute: typeof DeveloperToolsUrlDecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/password-generator': {
      id: '/developer-tools/password-generator'
      path: '/developer-tools/password-generator'
      fullPath: '/developer-tools/password-generator'
      preLoaderRoute: typeof DeveloperToolsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/json-validator': {
      id: '/developer-tools/json-validator'
      path: '/developer-tools/json-validator'
      fullPath: '/developer-tools/json-validator'
      preLoaderRoute: typeof DeveloperToolsJsonValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/json-formatter': {
      id: '/developer-tools/json-formatter'
      path: '/developer-tools/json-formatter'
      fullPath: '/developer-tools/json-formatter'
      preLoaderRoute: typeof DeveloperToolsJsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/js-minifier': {
      id: '/developer-tools/js-minifier'
      path: '/developer-tools/js-minifier'
      fullPath: '/developer-tools/js-minifier'
      preLoaderRoute: typeof DeveloperToolsJsMinifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/html-minifier': {
      id: '/developer-tools/html-minifier'
      path: '/developer-tools/html-minifier'
      fullPath: '/developer-tools/html-minifier'
      preLoaderRoute: typeof DeveloperToolsHtmlMinifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/css-minifier': {
      id: '/developer-tools/css-minifier'
      path: '/developer-tools/css-minifier'
      fullPath: '/developer-tools/css-minifier'
      preLoaderRoute: typeof DeveloperToolsCssMinifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/base64-encode': {
      id: '/developer-tools/base64-encode'
      path: '/developer-tools/base64-encode'
      fullPath: '/developer-tools/base64-encode'
      preLoaderRoute: typeof DeveloperToolsBase64EncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools/base64-decode': {
      id: '/developer-tools/base64-decode'
      path: '/developer-tools/base64-decode'
      fullPath: '/developer-tools/base64-decode'
      preLoaderRoute: typeof DeveloperToolsBase64DecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/weight': {
      id: '/calculators/weight'
      path: '/calculators/weight'
      fullPath: '/calculators/weight'
      preLoaderRoute: typeof CalculatorsWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/temperature': {
      id: '/calculators/temperature'
      path: '/calculators/temperature'
      fullPath: '/calculators/temperature'
      preLoaderRoute: typeof CalculatorsTemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/percentage': {
      id: '/calculators/percentage'
      path: '/calculators/percentage'
      fullPath: '/calculators/percentage'
      preLoaderRoute: typeof CalculatorsPercentageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/length': {
      id: '/calculators/length'
      path: '/calculators/length'
      fullPath: '/calculators/length'
      preLoaderRoute: typeof CalculatorsLengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/gst-vat': {
      id: '/calculators/gst-vat'
      path: '/calculators/gst-vat'
      fullPath: '/calculators/gst-vat'
      preLoaderRoute: typeof CalculatorsGstVatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/emi': {
      id: '/calculators/emi'
      path: '/calculators/emi'
      fullPath: '/calculators/emi'
      preLoaderRoute: typeof CalculatorsEmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/currency-converter': {
      id: '/calculators/currency-converter'
      path: '/calculators/currency-converter'
      fullPath: '/calculators/currency-converter'
      preLoaderRoute: typeof CalculatorsCurrencyConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/bmi': {
      id: '/calculators/bmi'
      path: '/calculators/bmi'
      fullPath: '/calculators/bmi'
      preLoaderRoute: typeof CalculatorsBmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/binary-to-decimal': {
      id: '/calculators/binary-to-decimal'
      path: '/calculators/binary-to-decimal'
      fullPath: '/calculators/binary-to-decimal'
      preLoaderRoute: typeof CalculatorsBinaryToDecimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/age': {
      id: '/calculators/age'
      path: '/calculators/age'
      fullPath: '/calculators/age'
      preLoaderRoute: typeof CalculatorsAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsAgeRoute: CalculatorsAgeRoute,
  CalculatorsBinaryToDecimalRoute: CalculatorsBinaryToDecimalRoute,
  CalculatorsBmiRoute: CalculatorsBmiRoute,
  CalculatorsCurrencyConverterRoute: CalculatorsCurrencyConverterRoute,
  CalculatorsEmiRoute: CalculatorsEmiRoute,
  CalculatorsGstVatRoute: CalculatorsGstVatRoute,
  CalculatorsLengthRoute: CalculatorsLengthRoute,
  CalculatorsPercentageRoute: CalculatorsPercentageRoute,
  CalculatorsTemperatureRoute: CalculatorsTemperatureRoute,
  CalculatorsWeightRoute: CalculatorsWeightRoute,
  DeveloperToolsBase64DecodeRoute: DeveloperToolsBase64DecodeRoute,
  DeveloperToolsBase64EncodeRoute: DeveloperToolsBase64EncodeRoute,
  DeveloperToolsCssMinifierRoute: DeveloperToolsCssMinifierRoute,
  DeveloperToolsHtmlMinifierRoute: DeveloperToolsHtmlMinifierRoute,
  DeveloperToolsJsMinifierRoute: DeveloperToolsJsMinifierRoute,
  DeveloperToolsJsonFormatterRoute: DeveloperToolsJsonFormatterRoute,
  DeveloperToolsJsonValidatorRoute: DeveloperToolsJsonValidatorRoute,
  DeveloperToolsPasswordGeneratorRoute: DeveloperToolsPasswordGeneratorRoute,
  DeveloperToolsUrlDecodeRoute: DeveloperToolsUrlDecodeRoute,
  DeveloperToolsUrlEncodeRoute: DeveloperToolsUrlEncodeRoute,
  ImageToolsBackgroundRemoverRoute: ImageToolsBackgroundRemoverRoute,
  ImageToolsCompressRoute: ImageToolsCompressRoute,
  ImageToolsCropRoute: ImageToolsCropRoute,
  ImageToolsImageToPdfRoute: ImageToolsImageToPdfRoute,
  ImageToolsJpgToPngRoute: ImageToolsJpgToPngRoute,
  ImageToolsPngToJpgRoute: ImageToolsPngToJpgRoute,
  ImageToolsQrCodeRoute: ImageToolsQrCodeRoute,
  ImageToolsResizeRoute: ImageToolsResizeRoute,
  ImageToolsRotateRoute: ImageToolsRotateRoute,
  ImageToolsWatermarkRoute: ImageToolsWatermarkRoute,
  TextToolsAiSummarizerRoute: TextToolsAiSummarizerRoute,
  TextToolsCaseConverterRoute: TextToolsCaseConverterRoute,
  TextToolsCharacterCounterRoute: TextToolsCharacterCounterRoute,
  TextToolsGrammarCheckerRoute: TextToolsGrammarCheckerRoute,
  TextToolsLoremIpsumRoute: TextToolsLoremIpsumRoute,
  TextToolsParaphraserRoute: TextToolsParaphraserRoute,
  TextToolsRemoveDuplicateLinesRoute: TextToolsRemoveDuplicateLinesRoute,
  TextToolsTextReverserRoute: TextToolsTextReverserRoute,
  TextToolsTextSorterRoute: TextToolsTextSorterRoute,
  TextToolsWordCounterRoute: TextToolsWordCounterRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
  DeveloperToolsIndexRoute: DeveloperToolsIndexRoute,
  ImageToolsIndexRoute: ImageToolsIndexRoute,
  PdfToolsIndexRoute: PdfToolsIndexRoute,
  TextToolsIndexRoute: TextToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
